### ISSUE TITLE
Compatibility with react-native without expo

### ISSUE THREAD

**Issue by carlowenig** [reggie3/react-native-webview-leaflet#35]
Hi there,
since the update to version 3 I encounter the problem, that react-native-webview-leaflet depends on expo.
Is this necessary or could it be changed with the next update?
I really depend on this library, but I don't want to use expo because of the big app size.

Thanks in advance!

**Comment by reggie3** [comment]
The reason Expo is currently included as a dependency is documented in the Expo forums here:
https://forums.expo.io/t/webview-unable-to-access-html-file-in-published-application/14092

To summarize, my published APK was unable to find the index file that contained the react-leaflet and leaflet.js code.  Even though the file was included, it was not able to be found using a standard `import` statement.

So, the bottom line is, how do we ensure the packaged index.html file is successfully able to be imported so that it can be used by the WebView.   Right now, it looks like Expo is the only way to satisfy that requirement.   However, I am still looking for alternatives, and am definitely open to suggestions.

**Comment by Peretz30** [comment]
Hey, @reggie3 ! I think, I have found solution, check this out 
https://github.com/facebook/react-native/issues/505

**Comment by reggie3** [comment]
@Peretz30 I saw that you made some changes in that section of WebViewLeaflet.js file in your fork.  Did you do those changes in order to implement the solution at that link?

**Comment by Peretz30** [comment]
@reggie3 yes, I experimented with it, but I still can't make this package working properly in my project. Now I am looking to react-native-maps with custom layers, but it's requed Google API key anyway, Thats very weird.

**Comment by forki** [comment]
any progress here?

**Comment by Peretz30** [comment]
@forki there is new fork of react-native-maps with OpenStreetMap support by default. I recommend to use it [react-native-maps-osmdroid](https://github.com/fqborges/react-native-maps)

**Comment by reggie3** [comment]
@forki @Peretz30 I've been pretty busy, and unable to address this issue. Maybe some time in the future, but it won't be any time soon.  I'll keep this issue open in case somebody wants to submit a pull request that addresses this issue.

**Comment by ethanx94** [comment]
Another problem with the Expo dependency is that Expo actually isn’t compatible with react-native-windows. I ended up just using a basic Webview and postMessaging any calls to the dom through strings and eval. It was a pretty ugly hack but it worked. I hope this library can break free of that dependency eventually.

Before I went the WebView route, I made an attempt at stripping away the dependency, it’s probably outdated by now but just a heads up 
https://github.com/ethanx94/react-native-webview-leaflet

**Comment by reggie3** [comment]
I think now that Expo has separated its dependencies into multiple packages, it should be possible to get by with just https://www.npmjs.com/package/expo-file-system vice the whole exp system.  I'm pretty busy at the moment but will try to take care of this in short order.

**Comment by DanielBoening** [comment]
Hi,
I'm looking forward to this change as we currently want to implement leaflet in our app. If there is anything I can do to help just let me know.

**Comment by schmem55** [comment]
Hi ,
Is there a possibility to use react-native-webview-leaflet without using expo? 
(react native app 0.59.10)
